sudo: required
services: 
  - docker
before_install:
  - docker build -t sjillen/docker-react -f Dockerfile.dev .
script:
  - docker run sjillen/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: docker-react
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-017832008036"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
